---
title: "Run Everything"
output:
  md_document:
    variant: markdown_github
  html_document:
    df_print: paged
---



```{r load_libraries}
library(here)
library(dplyr)
library(fs)
library(rmarkdown)
library(magrittr)
```

```{r set_paths, eval=FALSE, include=FALSE}
source("run_config.R")
```

```{r prepare_output_dir, eval=FALSE, include=FALSE}
if (dir_exists(out.dir)) {dir_delete(out.dir)}

regression_output_dir = file.path(out.dir, "full_run_html")
dir.create(regression_output_dir, recursive = TRUE)
```

```{r find_rmds2, eval=FALSE, include=TRUE}
list.files("../misc/downloading", pattern = ".Rmd", full.names = TRUE) %>%
  paste(collapse = '", "') %>%
  print
```

```{r find_rmds, eval=FALSE, include=TRUE}
list.files(".", pattern = ".Rmd", full.names = TRUE) %>%
  paste(collapse = '", "') %>%
  print
```

```{r choose_regerssion_rmds}
regression_rmds_1pct = c("../misc/downloading/atacama_1pct_download.Rmd",
                    "../misc/downloading/download_dada_references.Rmd",
                    "./demultiplex_tutorial.Rmd",
                    "./dada2_tutorial_1_6.Rmd",
                    "./alpha_diversity.Rmd",
                    "./absolute_abundance_plots.Rmd",
                    "./relative_abundance.Rmd")
# The ordination Rmd has a problem with the atacama_1pct.rds.  It works with the atacama_10pct.rds
# ,
#                     "./ordination.Rmd"
#                     )
```

```{r run_render}
render_params = list(
  atacama_ps_rds=path_real("~/scratch/atacama_1pct/dada2/atacama_1pct.rds")
)
render_outdir=path_real("~/scratch/atacama_1pct_render_run/")
dir_create(render_outdir)
for (cur_rmd in regression_rmds){
  print(cur_rmd)
  render(cur_rmd, 
         output_format="html_document",
         params=render_params,
         output_dir=render_outdir)
}
```

```{r regerssion_rmds_10pct}
regression_rmds_10pct = c("../misc/downloading/atacama_10pct_download.Rmd",
                    "../misc/downloading/download_dada_references.Rmd",
                    "./demultiplex_tutorial.Rmd",
                    "./dada2_tutorial_1_6.Rmd",
                    "./alpha_diversity.Rmd",
                    "./absolute_abundance_plots.Rmd",
                    "./relative_abundance.Rmd",
                    "./ordination.Rmd"
                    )
```




# SessionInfo
```{r session_info}
sessionInfo()
```


