---
title: "Run Everything"
output:
  md_document:
    variant: markdown_github
  html_document:
    df_print: paged
---



```{r load_libraries}
library(here)
library(dplyr)
library(fs)
library(rmarkdown)
library(magrittr)
```


```{r choose_regerssion_rmds}
regression_rmds_10pct = c("../misc/downloading/atacama_download.Rmd",
                    "../misc/downloading/download_dada_references.Rmd",
                    "./demultiplex_tutorial.Rmd",
                    "./dada2_tutorial_1_6.Rmd",
                    "./alpha_diversity.Rmd",
                    "./absolute_abundance_plots.Rmd",
                    "./relative_abundance.Rmd",
                    "./ordination.Rmd")
regression_rmds_10pct = regression_rmds_10pct[4]

render_params = list(
  atacama_data_percent="10",
  data_dir=path.expand("~/scratch/test/data"))
render_outdir=path_real("~/scratch/atacama_10pct_render_run/")
dir_create(render_outdir)
for (cur_rmd in regression_rmds_10pct){
  print(cur_rmd)
  render(cur_rmd, 
         output_format="html_document",
         params=render_params,
         output_dir=render_outdir)
}
```



# SessionInfo
```{r session_info}
sessionInfo()
```


