---
title: "Download Atacama Data"
output:
  md_document:
    variant: markdown_github
---

# Paths, Directories, and Shell Variables
To keep the code readable and portable, it is nice to assign paths to variables.  We also need to use the R `Sys.setenv` command to make shell variables that can be used in the bash chunks below.

```{r files_and_directories}
# Directories

data.dir = "/data/tutorial_data"
atacama.10pct.dir = file.path(data.dir, "atacama_10pct")
dir.create(atacama.10pct.dir, recursive = TRUE)

# Set variables for bash
Sys.setenv(ATACAMA_10PCT_DIR = atacama.10pct.dir)
```

# Download Data
https://docs.qiime2.org/2018.11/tutorials/atacama-soils/#subsample-data




```{bash}
# set -u
wget --no-verbose --directory-prefix $ATACAMA_10PCT_DIR \
  https://data.qiime2.org/2018.11/tutorials/atacama-soils/sample_metadata.tsv \
  https://data.qiime2.org/2018.11/tutorials/atacama-soils/10p/forward.fastq.gz \
  https://data.qiime2.org/2018.11/tutorials/atacama-soils/10p/reverse.fastq.gz \
  https://data.qiime2.org/2018.11/tutorials/atacama-soils/10p/barcodes.fastq.gz
```
```{bash}
cd $ATACAMA_10PCT_DIR
md5sum * > md5sum.txt
```

# Make the data directory read-only
```{bash}
chmod -R a-w $ATACAMA_1PCT_DIR
chmod -R a-w $ATACAMA_10PCT_DIR
```

# Session Info
Always print `sessionInfo` for reproducibility!
```{r}
sessionInfo()
```

