---
title: "Download Atacama Data"
params:
  atacama_data_percent: 1
  data_dir : /data/tutorial_data
output:
  md_document:
    variant: markdown_github
---

# Paths, Directories, and Shell Variables
To keep the code readable and portable, it is nice to assign paths to variables.  We also need to use the R `Sys.setenv` command to make shell variables that can be used in the bash chunks below.


```{r files_and_directories, include=FALSE}
# Params

if(exists("params") && 
   !is.null(params[["atacama_data_percent"]])){
  atacama.data.percent=params[["atacama_data_percent"]]
} else {
  atacama.data.percent = "1"
}
if(exists("params") && 
   !is.null(params[["data_dir"]])){
  data.dir=params[["data_dir"]]
} else {
  data.dir = "/data/tutorial_data"
}

# Directories

atacama.data.dir = file.path(data.dir, paste0("atacama_", atacama.data.percent, "pct"))
dir.create(atacama.data.dir, recursive = TRUE)

url_base = "https://data.qiime2.org/2018.11/tutorials/atacama-soils"
data_urls = c(paste(url_base, "sample_metadata.tsv", sep="/"),
              paste(url_base, paste0(atacama.data.percent,"p"), "forward.fastq.gz", sep="/"),
              paste(url_base, paste0(atacama.data.percent,"p"), "reverse.fastq.gz", sep="/"),
              paste(url_base, paste0(atacama.data.percent,"p"), "barcodes.fastq.gz", sep="/")
)


# Set variables for bash
Sys.setenv(ATACAMA_DATA_DIR = atacama.data.dir)
Sys.setenv(ATACAMA_URLS = paste(data_urls, collapse = " "))

```

# Download Data
https://docs.qiime2.org/2018.11/tutorials/atacama-soils/#subsample-data

```{bash}
# set -u
wget --no-verbose --directory-prefix $ATACAMA_DATA_DIR $ATACAMA_URLS
```

```{bash}
cd $ATACAMA_DATA_DIR
md5sum * > md5sum.txt
```

# Make the data directory read-only
```{bash}
chmod -R a-w $ATACAMA_DATA_DIR
```

# Session Info
Always print `sessionInfo` for reproducibility!
```{r}
sessionInfo()
```

